### ISSUE TITLE
update to @loadable/components package

### ISSUE THREAD

**Issue by mokipedia** [stratiformltd/react-loadable-visibility#22]
**Do you want to request a feature or report a bug?**
feature / enhancement

**What is the current behaviour?**

loadable-components package is used

**Desired behaviour**

should use @loadable/component

As loadable-components are now @loadable/component and the old one is deprecated, please update to the new dependency, as your import breaks with the new version (name change).

**Comment by tazsingh** [comment]
Sorry for the late response! I posted this to Twitter hoping that someone would jump in on the PR as it should be a simple fix.

If you and/or someone else wants to tackle this, it should be as simple as updating the dep and making sure the test suite passes. Happy to review the PR and assist with getting it merged! It may be a little while before I have a chance to do this myself.

Thanks!

**Comment by sauravvarma** [comment]
@tazsingh Are there any plans to fix it any time soon? I am assuming it only needs a name change in package.json dependency and loadable-components.js import statement?

Thank you!
