### ISSUE TITLE
Failed to execute 'unobserve' on 'Intersection Observer'

### ISSUE THREAD

**Issue by sauravvarma** [stratiformltd/react-loadable-visibility#24]
Upon debugging it seems like the ref isn't getting created in LoadableVisibilityComponent.

My current setup:
- React 16.8.6
- Loadable Components for code-splitting with SSR
- Webpack

**Comment by tazsingh** [comment]
In the future, please provide a reproducible build. It took me a considerable amount of time to create this Sandbox - https://codesandbox.io/s/us49e

I've pushed a fix. Will be released in 3.0.1.

**Comment by sauravvarma** [comment]
My apologies, I didn't realise you meant a sample app (I'm fairly new to this) or thought it was going to be tough task reproducing it. I'll definitely provide reproducible sandbox examples for the few bugs I have encountered after this version.

Thank you so much, you've been kind and really helpful.
