### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by dbartholomae** [stratiformltd/react-loadable-visibility#27]
Hi there,

would you be interested in a PR that adds TypeScript typings?

Best,
Daniel

**Comment by tazsingh** [comment]
Of course!

**Comment by dbartholomae** [comment]
Since the types of `react-loadable` are currently managed via `DefinitelyTyped` and I wouldn't want to couple this library to a helper library, I have also written a [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37908) to `DefinitelyTyped` instead of this one. When it gets merged, types for `react-loadable-visibility` should be available from `@types/react-loadable-visibility`. The PR might take some time though since I have a problem with the typings of `react-loadable` itself that I currently cannot solve on my own.

**Comment by dbartholomae** [comment]
Typings are available now via DefinitivelyTyped

**Comment by tazsingh** [comment]
@dbartholomae Amazing! Thanks for getting that done 💪 

If you want to add instructions to the `README` on how to get that working, I'd be happy to review a PR that adds that in. Let me know as you'll likely get to it before I have a chance to 😅

**Comment by dbartholomae** [comment]
Shouldn't be necessary, it is the default way to add typings for repos that don't have typings, and TypeScript itself will guide you to it :)
