### ISSUE TITLE
window is not defined on server side

### ISSUE THREAD

**Issue by s524797336** [stratiformltd/react-loadable-visibility#4]
capacities.js
var IntersectionObserver = exports.IntersectionObserver = window && window.IntersectionObserver;
on server side will throw error window is not defined
Can you change to this?
var IntersectionObserver = exports.IntersectionObserver = typeof window !== 'undefined' && window.IntersectionObserver;

**Comment by tazsingh** [comment]
Looks like a reasonable change to me. I’ll make this change and publish a new version when I get a chance but would also be happy to accept a pull request!

**Comment by s524797336** [comment]
Publish it to npm ASAP would be very helpful, thank you very much
