### ISSUE TITLE
Always render all contents during SSR?

### ISSUE THREAD

**Issue by fikriauliya** [stratiformltd/react-loadable-visibility#9]
Inspecting the raw HTML returned from SSR, it seems this library doesn't return the not-yet-visible content (e.g. Footer) as part of SSR response. In our use case, we need to render all `LoadableVisibility`-wrapped components during SSR. Is it currently possible?

**Comment by tazsingh** [comment]
Yes it will be the same way that you would render `react-loadable` or `loadable-components` from the server. `react-loadable-visibility` will just return the underlying component on the server where the `IntersectionObserver` API is not available - https://github.com/stratiformltd/react-loadable-visibility#how-does-this-work

I've used this approach with `react-loadable` on my own website which is statically rendered and you can refer to the code there as an example - https://github.com/stratiformltd/website

Hope that helps!
